export const UPDATE_SCORE_STARTED = 'UPDATE_SCORE_STARTED';
export const UPDATE_SCORE_SUCCESS = 'UPDATE_SCORE_SUCCESS';
export const UPDATE_SCORE_FAILURE_NETWORK = 'UPDATE_SCORE_FAILURE_NETWORK';
export const UPDATE_SCORE_DEFAULT = 'UPDATE_SCORE_DEFAULT';